name: Deploy React App

on:
  push:
    branches:
      - main  # or 'master' or any branch you want to deploy from

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 23.6.1  # or any LTS version you prefer

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # replace with your bucket's region if needed

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://hnl-website --delete
        # --delete removes files that are no longer in your build/ folder